exo1-1:
	xmllint --noout --dtdvalid dtd1-1.dtd xml1-1.xml 

exo1-2:
	xmllint --noout --dtdvalid dtd1-2.dtd xml1-2.xml 

exo2-1:
	xmllint --noout --dtdvalid dtd2-1.dtd xml2-1.xml 

exo2-2:
	xmllint --noout --dtdvalid dtd2-2.dtd xml2-2.xml 

exo2-3:
	xmllint --noout --dtdvalid dtd2-3.dtd xml2-3.xml 

exo2-4:
	xmllint --noout --dtdvalid dtd2-4.dtd xml2-4.xml 

exo2-5:
	xmllint --noout --dtdvalid dtd2-5.dtd xml2-5.xml 

exo2-6:
	xmllint --noout --dtdvalid dtd2-6.dtd xml2-6.xml 
